In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import warnings; warnings.simplefilter('ignore')
from sklearn.preprocessing import StandardScaler

In [2]:
train = pd.read_csv("10-best features/10-best Training-Testing split/UNSW_2018_IoT_Botnet_Final_10_best_Training.csv")
test = pd.read_csv("10-best features/10-best Training-Testing split/UNSW_2018_IoT_Botnet_Final_10_best_Testing.csv")

In [3]:
train.head()

pkSeqID proto            saddr  sport          daddr dport     seq  \
0  3142762   udp  192.168.100.150   6551  192.168.100.3    80  251984   
1  2432264   tcp  192.168.100.150   5532  192.168.100.3    80  256724   
2  1976315   tcp  192.168.100.147  27165  192.168.100.3    80   62921   
3  1240757   udp  192.168.100.150  48719  192.168.100.3    80   99168   
4  3257991   udp  192.168.100.147  22461  192.168.100.3    80  105063   

     stddev  N_IN_Conn_P_SrcIP       min  state_number      mean  \
0  1.900363                100  0.000000             4  2.687519   
1  0.078003                 38  3.856930             3  3.934927   
2  0.268666                100  2.974100             3  3.341429   
3  1.823185                 63  0.000000             4  3.222832   
4  0.822418                100  2.979995             4  3.983222   

   N_IN_Conn_P_DstIP  drate     srate       max  attack category subcategory  
0                100    0.0  0.494549  4.031619       1     DDoS         UDP  
1                100    0.0  0.256493  4.012924       1     DDoS         TCP  
2                100    0.0  0.294880  3.609205       1     DDoS         TCP  
3                 63    0.0  0.461435  4.942302       1      DoS         UDP  
4                100    0.0  1.002999  4.994452       1     DDoS         UDP

In [4]:
test.head()

pkSeqID proto            saddr  sport          daddr dport     seq  \
0   792371   udp  192.168.100.150  48516  192.168.100.3    80  175094   
1  2056418   tcp  192.168.100.148  22267  192.168.100.3    80  143024   
2  2795650   udp  192.168.100.149  28629  192.168.100.3    80  167033   
3  2118009   tcp  192.168.100.148  42142  192.168.100.3    80  204615   
4   303688   tcp  192.168.100.149   1645  192.168.100.5    80   40058   

     stddev  N_IN_Conn_P_SrcIP       min  state_number      mean  \
0  0.226784                100  4.100436             4  4.457383   
1  0.451998                100  3.439257             1  3.806172   
2  1.931553                 73  0.000000             4  2.731204   
3  0.428798                 56  3.271411             1  3.626428   
4  2.058381                100  0.000000             3  1.188407   

   N_IN_Conn_P_DstIP     drate     srate       max  attack category  \
0                100  0.000000  0.404711  4.719438       1      DoS   
1                100  0.225077  0.401397  4.442930       1     DDoS   
2                100  0.000000  0.407287  4.138455       1     DDoS   
3                100  0.000000  0.343654  4.229700       1     DDoS   
4                100  0.000000  0.135842  4.753628       1      DoS   

  subcategory  
0         UDP  
1         TCP  
2         UDP  
3         TCP  
4         TCP

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2934817 entries, 0 to 2934816
Data columns (total 19 columns):
 #   Column             Dtype  
---  ------             -----  
 0   pkSeqID            int64  
 1   proto              object 
 2   saddr              object 
 3   sport              object 
 4   daddr              object 
 5   dport              object 
 6   seq                int64  
 7   stddev             float64
 8   N_IN_Conn_P_SrcIP  int64  
 9   min                float64
 10  state_number       int64  
 11  mean               float64
 12  N_IN_Conn_P_DstIP  int64  
 13  drate              float64
 14  srate              float64
 15  max                float64
 16  attack             int64  
 17  category           object 
 18  subcategory        object 
dtypes: float64(6), int64(6), object(7)
memory usage: 425.4+ MB


In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 733705 entries, 0 to 733704
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   pkSeqID            733705 non-null  int64  
 1   proto              733705 non-null  object 
 2   saddr              733705 non-null  object 
 3   sport              733705 non-null  object 
 4   daddr              733705 non-null  object 
 5   dport              733705 non-null  object 
 6   seq                733705 non-null  int64  
 7   stddev             733705 non-null  float64
 8   N_IN_Conn_P_SrcIP  733705 non-null  int64  
 9   min                733705 non-null  float64
 10  state_number       733705 non-null  int64  
 11  mean               733705 non-null  float64
 12  N_IN_Conn_P_DstIP  733705 non-null  int64  
 13  drate              733705 non-null  float64
 14  srate              733705 non-null  float64
 15  max                733705 non-null  float64
 16  at

In [7]:
train.shape

(2934817, 19)

In [8]:
test.shape

(733705, 19)

In [9]:
train.isnull().sum()

pkSeqID              0
proto                0
saddr                0
sport                0
daddr                0
dport                0
seq                  0
stddev               0
N_IN_Conn_P_SrcIP    0
min                  0
state_number         0
mean                 0
N_IN_Conn_P_DstIP    0
drate                0
srate                0
max                  0
attack               0
category             0
subcategory          0
dtype: int64

In [10]:
test.isnull().sum()

pkSeqID              0
proto                0
saddr                0
sport                0
daddr                0
dport                0
seq                  0
stddev               0
N_IN_Conn_P_SrcIP    0
min                  0
state_number         0
mean                 0
N_IN_Conn_P_DstIP    0
drate                0
srate                0
max                  0
attack               0
category             0
subcategory          0
dtype: int64

In [11]:
train.drop(["pkSeqID","seq","subcategory"], axis=1, inplace=True)

In [12]:
test.drop(["pkSeqID","seq","subcategory"], axis=1, inplace=True)

In [13]:
train.dtypes[train.dtypes=='object']

proto       object
saddr       object
sport       object
daddr       object
dport       object
category    object
dtype: object

In [14]:
train['proto'].value_counts()

udp          1596819
tcp          1330598
icmp            7228
arp              166
ipv6-icmp          6
Name: proto, dtype: int64

In [15]:
train['saddr'].value_counts()

192.168.100.147              761360
192.168.100.148              738642
192.168.100.150              712260
192.168.100.149              711466
192.168.100.3                  6609
192.168.100.5                  4107
192.168.100.6                   272
192.168.100.7                    34
192.168.100.4                    17
192.168.100.1                    14
192.168.100.27                    9
192.168.100.46                    8
fe80::250:56ff:febe:254           5
192.168.100.55                    3
fe80::2c6a:ff9b:7e14:166a         2
fe80::c0c0:aa20:45b9:bdd9         2
fe80::250:56ff:febe:89ee          2
fe80::250:56ff:febe:26db          2
fe80::250:56ff:febe:c038          2
fe80::250:56ff:febe:e9d9          1
Name: saddr, dtype: int64

In [16]:
train['sport'].value_counts()

0x0303    7156
80        3220
1822       878
60541      869
1216       868
          ... 
27738       31
39305       30
18992       30
0x000d      10
0x0011       8
Name: sport, Length: 65541, dtype: int64

In [17]:
train['daddr'].value_counts()

192.168.100.3      1900562
192.168.100.5       361192
192.168.100.7       332161
192.168.100.6       329679
192.168.100.150       3040
                    ...   
205.251.194.201          1
205.251.192.170          1
205.251.194.154          1
205.251.194.102          1
192.55.83.30             1
Name: daddr, Length: 81, dtype: int64

In [18]:
train['dport'].value_counts()

80       2858794
1           5379
3306        3757
53           275
-1           166
          ...   
4527           1
25883          1
39984          1
6413           1
6533           1
Name: dport, Length: 6906, dtype: int64

In [19]:
train['category'].value_counts()

DDoS              1541315
DoS               1320148
Reconnaissance      72919
Normal                370
Theft                  65
Name: category, dtype: int64

In [20]:
test['category'].value_counts()

DDoS              385309
DoS               330112
Reconnaissance     18163
Normal               107
Theft                 14
Name: category, dtype: int64

In [21]:
drop_theft = train[train['category']=='Theft'].index
train.drop(drop_theft , inplace=True)

In [22]:
drop_theft = test[test['category']=='Theft'].index
test.drop(drop_theft , inplace=True)

In [23]:
search_string='0x'
result = set([i for i in train['sport'] if i.startswith(search_string)])
result

{'0x0008', '0x000d', '0x0011', '0x0303'}

In [24]:
train['sport']=train['sport'].replace(['0x0303'],'771') 
train['sport']=train['sport'].replace(['0x0011'],'17')
train['sport']=train['sport'].replace(['0x000d'],'13')
train['sport']=train['sport'].replace(['0x0008'],'8')

In [25]:
train["sport"] = train["sport"].astype(str).astype(int)

In [26]:
search_string='0x'
result = set([i for i in train['dport'] if i.startswith(search_string)])
print(len(result))
result

1062


{'0x2500',
 '0x01cc',
 '0x984e',
 '0x0504',
 '0xa146',
 '0xb583',
 '0x021f',
 '0x0b04',
 '0xc641',
 '0x3a12',
 '0x1e80',
 '0xcc05',
 '0x1891',
 '0x6f02',
 '0x6bc0',
 '0x6ff4',
 '0x3941',
 '0x5379',
 '0x86e4',
 '0x1504',
 '0x6ef0',
 '0xe650',
 '0x2c4c',
 '0xa876',
 '0x8a13',
 '0xd24a',
 '0x334e',
 '0x7100',
 '0x5543',
 '0x47bd',
 '0x21c0',
 '0x3686',
 '0x5a45',
 '0xe00c',
 '0x6e8d',
 '0x7a42',
 '0x5151',
 '0xe74c',
 '0x3dc0',
 '0x2404',
 '0x2238',
 '0x2ac0',
 '0x8703',
 '0x3442',
 '0x04c0',
 '0x2b42',
 '0x9201',
 '0x677a',
 '0x0403',
 '0x00fe',
 '0x8603',
 '0x2767',
 '0x4e4a',
 '0x1204',
 '0xd001',
 '0x09c0',
 '0x0944',
 '0x75b2',
 '0x3548',
 '0x3bc0',
 '0x8c54',
 '0x4854',
 '0x19c0',
 '0x9643',
 '0xbba8',
 '0x208e',
 '0xe903',
 '0x1304',
 '0x997e',
 '0x954c',
 '0x494a',
 '0x02f4',
 '0x9526',
 '0x1503',
 '0xa355',
 '0xa100',
 '0x81b1',
 '0xec0b',
 '0x984a',
 '0x5255',
 '0xaa02',
 '0x1260',
 '0x2e40',
 '0x0c03',
 '0x3ec0',
 '0xc342',
 '0xf448',
 '0x800d',
 '0x4a82',
 '0x62a0',
 '0x3c44',

In [27]:
train['dport']=train.dport.apply(lambda x: int(x,16) if len(x)>1 and x[1]=="x" else int(x))

In [28]:
train['dport'].value_counts()

 80       2858794
 1           5379
 3306        3757
 53           275
-1            163
           ...   
 13445          1
 6636           1
 29153          1
 29152          1
 8863           1
Name: dport, Length: 6778, dtype: int64

In [29]:
test['sport']=test['sport'].replace(['0x0303'],'771') 
test['sport']=test['sport'].replace(['0x0011'],'17')
test['sport']=test['sport'].replace(['0x000d'],'13')
test['sport']=test['sport'].replace(['0x0008'],'8')

In [30]:
test["sport"] = test["sport"].astype(str).astype(int)

In [31]:
test['dport'] = test.dport.apply(lambda x: int(x,16) if len(x)>1 and x[1]=="x" else int(x))

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train["saddr_enc"]= le.fit_transform(train.saddr)
train["daddr_enc"]= le.fit_transform(train.daddr)
train["proto_enc"]= le.fit_transform(train.proto)
train["category_enc"]= le.fit_transform(train.category)
train.drop(['saddr','daddr','proto','category'], axis=1, inplace=True)

In [33]:
test["saddr_enc"]= le.fit_transform(test.saddr)
test["daddr_enc"]= le.fit_transform(test.daddr)
test["proto_enc"]= le.fit_transform(test.proto)
test["category_enc"]= le.fit_transform(test.category)
test.drop(['saddr','daddr','proto','category'], axis=1, inplace=True)

In [34]:
train.head()

sport  dport    stddev  N_IN_Conn_P_SrcIP       min  state_number  \
0   6551     80  1.900363                100  0.000000             4   
1   5532     80  0.078003                 38  3.856930             3   
2  27165     80  0.268666                100  2.974100             3   
3  48719     80  1.823185                 63  0.000000             4   
4  22461     80  0.822418                100  2.979995             4   

       mean  N_IN_Conn_P_DstIP  drate     srate       max  attack  saddr_enc  \
0  2.687519                100    0.0  0.494549  4.031619       1          4   
1  3.934927                100    0.0  0.256493  4.012924       1          4   
2  3.341429                100    0.0  0.294880  3.609205       1          1   
3  3.222832                 63    0.0  0.461435  4.942302       1          4   
4  3.983222                100    0.0  1.002999  4.994452       1          1   

   daddr_enc  proto_enc  category_enc  
0         15          4             0  
1         15          3             0  
2         15          3             0  
3         15          4             1  
4         15          4             0

In [35]:
train['category_enc'].value_counts()

0    1541315
1    1320148
3      72919
2        370
Name: category_enc, dtype: int64

In [36]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2934752 entries, 0 to 2934816
Data columns (total 16 columns):
 #   Column             Dtype  
---  ------             -----  
 0   sport              int32  
 1   dport              int64  
 2   stddev             float64
 3   N_IN_Conn_P_SrcIP  int64  
 4   min                float64
 5   state_number       int64  
 6   mean               float64
 7   N_IN_Conn_P_DstIP  int64  
 8   drate              float64
 9   srate              float64
 10  max                float64
 11  attack             int64  
 12  saddr_enc          int32  
 13  daddr_enc          int32  
 14  proto_enc          int32  
 15  category_enc       int32  
dtypes: float64(6), int32(5), int64(5)
memory usage: 324.7 MB


In [37]:
y_train=train["category_enc"]

In [38]:
y_test=test["category_enc"]

In [39]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
features = train.iloc[:,:-1]
cols=features.columns
scaled_features= scaler.fit_transform(features)
train= pd.DataFrame(scaled_features,columns=cols)

In [40]:
features = test.iloc[:,:-1]
cols=features.columns
scaled_features= scaler.fit_transform(features)
test= pd.DataFrame(scaled_features,columns=cols)

In [41]:
train.head()

sport     dport    stddev  N_IN_Conn_P_SrcIP       min  state_number  \
0 -1.380796 -0.094028  1.260991           0.715435 -0.685661      0.729327   
1 -1.434107 -0.094028 -1.006649          -1.826659  1.914132     -0.113083   
2 -0.302346 -0.094028 -0.769399           0.715435  1.319054     -0.113083   
3  0.825282 -0.094028  1.164956          -0.801621 -0.685661      0.729327   
4 -0.548442 -0.094028 -0.080342           0.715435  1.323028      0.729327   

       mean  N_IN_Conn_P_DstIP    drate     srate       max    attack  \
0  0.301113           0.415159 -0.00763 -0.003355  0.543986  0.011229   
1  1.122991           0.415159 -0.00763 -0.003659  0.533940  0.011229   
2  0.731954           0.415159 -0.00763 -0.003610  0.316991  0.011229   
3  0.653814          -1.621898 -0.00763 -0.003397  1.033365  0.011229   
4  1.154811           0.415159 -0.00763 -0.002707  1.061389  0.011229   

   saddr_enc  daddr_enc  proto_enc  
0   1.301786  -0.638504   0.897321  
1   1.301786  -0.638504  -1.049199  
2  -1.281470  -0.638504  -1.049199  
3   1.301786  -0.638504   0.897321  
4  -1.281470  -0.638504   0.897321

In [42]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2934752 entries, 0 to 2934751
Data columns (total 15 columns):
 #   Column             Dtype  
---  ------             -----  
 0   sport              float64
 1   dport              float64
 2   stddev             float64
 3   N_IN_Conn_P_SrcIP  float64
 4   min                float64
 5   state_number       float64
 6   mean               float64
 7   N_IN_Conn_P_DstIP  float64
 8   drate              float64
 9   srate              float64
 10  max                float64
 11  attack             float64
 12  saddr_enc          float64
 13  daddr_enc          float64
 14  proto_enc          float64
dtypes: float64(15)
memory usage: 335.9 MB


In [43]:
y_train.value_counts()

0    1541315
1    1320148
3      72919
2        370
Name: category_enc, dtype: int64

In [44]:
from sklearn import model_selection
from sklearn.model_selection import StratifiedKFold,cross_val_score
from sklearn.svm import SVC

In [ ]:
# model = SVC(verbose=1,random_state=42)
# model.fit(train,y_train)
# score = model.score(test,y_test)
# score

In [ ]:
# from sklearn.metrics import classification_report,confusion_matrix
# prediction = model.predict(test)
# print(classification_report(y_test,prediction))

In [ ]:
# print(confusion_matrix(y_test,prediction))

In [45]:
import imblearn
from imblearn.over_sampling import RandomOverSampler
samp_strat= { 0 : 1541315, 1 : 1320148, 2 : 72919, 3 : 72919}
random_over= RandomOverSampler(sampling_strategy=samp_strat,random_state=1)
Xres,yres = random_over.fit_resample(train,y_train)

In [46]:
pd.Series(yres).value_counts()

0    1541315
1    1320148
3      72919
2      72919
Name: category_enc, dtype: int64

In [47]:
import imblearn
from imblearn.under_sampling import RandomUnderSampler
samp_strat= { 0 : 72919, 1 : 72919, 2 : 72919, 3 : 72919}
random_under= RandomUnderSampler(sampling_strategy=samp_strat,random_state=1)
Xres1,yres1 = random_under.fit_resample(Xres,yres)

In [48]:
pd.Series(yres1).value_counts()

3    72919
2    72919
1    72919
0    72919
Name: category_enc, dtype: int64

In [49]:
model = SVC(verbose=1,random_state=42)
model.fit(Xres1,yres1)
score = model.score(test,y_test)
score

[LibSVM]

0.8990678637191951

In [50]:
from sklearn.metrics import classification_report,confusion_matrix
prediction = model.predict(test)
print(classification_report(y_test,prediction))


              precision    recall  f1-score   support

           0       0.89      0.93      0.91    385309
           1       1.00      0.86      0.92    330112
           2       1.00      0.99      1.00       107
           3       0.38      0.93      0.54     18163

    accuracy                           0.90    733691
   macro avg       0.82      0.93      0.84    733691
weighted avg       0.92      0.90      0.91    733691



In [51]:
print(confusion_matrix(y_test,prediction))

[[359050    157      0  26102]
 [ 44781 283591      0   1740]
 [     0      0    106      1]
 [   339    933      0  16891]]


In [53]:
model = SVC()
skf = StratifiedKFold(n_splits=10,shuffle=True,random_state=42)
scores = cross_val_score(model,Xres1,yres1,scoring='accuracy',cv=skf)

In [54]:
scores

array([0.92594624, 0.93043747, 0.92995749, 0.92868897, 0.93006034,
       0.92892896, 0.92405801, 0.92659512, 0.92724655, 0.92830939])

In [55]:
from numpy import mean
mean(scores)

0.9280228545291823

In [57]:
params = {'gamma':[0.01,0.1],'C':(1,10)}
from sklearn.model_selection import GridSearchCV
model1 = SVC(random_state=42)
gscv = GridSearchCV(model1,params,verbose=3,cv=3)
gscv.fit(Xres1,yres1)
print("best score:",gscv.best_score_)
print("best params:",gscv.best_params_)

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] C=1, gamma=0.01 .................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ..................... C=1, gamma=0.01, score=0.985, total= 2.8min
[CV] C=1, gamma=0.01 .................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.8min remaining:    0.0s


[CV] ..................... C=1, gamma=0.01, score=0.985, total= 2.9min
[CV] C=1, gamma=0.01 .................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  5.7min remaining:    0.0s


[CV] ..................... C=1, gamma=0.01, score=0.985, total= 2.8min
[CV] C=1, gamma=0.1 ..................................................
[CV] ...................... C=1, gamma=0.1, score=0.993, total= 5.0min
[CV] C=1, gamma=0.1 ..................................................
[CV] ...................... C=1, gamma=0.1, score=0.993, total= 5.2min
[CV] C=1, gamma=0.1 ..................................................
[CV] ...................... C=1, gamma=0.1, score=0.993, total= 5.5min
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.990, total= 1.4min
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.990, total= 1.4min
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.990, total= 1.3min
[CV] C=10, gamma=0.1 .................................................
[CV] .

[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed: 36.9min finished


best score: 0.9973703695920392
best params: {'C': 10, 'gamma': 0.1}
